# Generated by Django 2.1.5 on 2019-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('T', 'Twitter'), ('WB', 'Weibo'), ('WC', 'Wechat'), ('B', 'BiliBili'), ('H', 'Huodongxing'), ('G', 'GitHub')], max_length=20)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
