# Generated by Django 2.1.5 on 2019-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(choices=[('T', 'Twitter'), ('WB', 'Weibo'), ('WC', 'Wechat'), ('B', 'BiliBili'), ('H', 'Huodongxing'), ('G', 'GitHub'), ('J', 'Jianshu')], max_length=20),
        ),
    ]
