# Generated by Django 2.1.5 on 2019-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregation', '0002_auto_20190427_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.CharField(max_length=200),
        ),
    ]
